---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy-conclusion.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization 
summary: 'La solution fournit les étapes nécessaires au déploiement d"Hyper-V sur le stockage NetApp' 
---
= Résumé du déploiement de Microsoft Hyper-V sur les systèmes de stockage ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP est la base de stockage partagé optimale pour déployer une variété de charges de travail informatiques.  Les plates-formes ONTAP AFF ou ASA sont à la fois flexibles et évolutives pour de multiples cas d'utilisation et applications.  Windows Server 2022 et Hyper-V activé constituent un cas d’utilisation courant en tant que solution de virtualisation, décrit dans ce document.  La flexibilité et l'évolutivité du stockage ONTAP et des fonctionnalités associées permettent aux clients de démarrer avec une couche de stockage de taille adaptée, capable de croître et de s'adapter à l'évolution de leurs besoins commerciaux.  Dans les conditions actuelles du marché, Hyper-V offre une option d’hyperviseur alternatif parfaite qui fournit la plupart des fonctionnalités fournies par VMware.
