---
sidebar: sidebar 
permalink: migration/migrate-get-start-ontap.html 
keywords: migration, getting, started, ontap datastores, netapp 
summary:  
---
= En savoir plus sur la migration de machines virtuelles vers des banques de données ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La migration des charges de travail VMware vers ONTAP améliore la gestion des données et les performances grâce à des fonctionnalités telles que la déduplication, la compression et les instantanés.

Cette migration permet une intégration transparente, une meilleure protection des données et une plus grande flexibilité dans la gestion des environnements virtualisés, garantissant une transition en douceur avec un temps d'arrêt minimal.



== Cas d'utilisation

Il existe de nombreuses options de migration en termes de source et de destination lorsque l'on envisage de migrer vers des magasins de données basés sur ONTAP .

* Migration de systèmes de stockage tiers (y compris vSAN) vers des banques de données ONTAP .
* Migration de machines virtuelles dans le même cluster vSphere
* Migration de machines virtuelles sur plusieurs clusters vSphere
* Migration de machines virtuelles entre serveurs vCenter dans le même domaine SSO
* Migration de machines virtuelles entre serveurs vCenter dans différents domaines SSO
* Migration de machines virtuelles entre différents centres de données
* Migration de systèmes de stockage tiers (y compris vSAN) vers des banques de données ONTAP .
* Migration de machines virtuelles dans un environnement cloud hybride


Pour plus d'informations sur la migration des charges de travail VMware vers des banques de données basées sur ONTAP , consultez lelink:migrate-vms-to-ontap-datastore.html["Migrer des machines virtuelles vers des banques de données ONTAP"] .
