---
sidebar: sidebar 
permalink: proxmox/proxmox-ontap.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, ontap, storage, aff 
summary: 'Provisionnez le stockage ONTAP pour l"environnement virtuel Proxmox (VE) en utilisant les protocoles NAS (NFS, SMB) et les protocoles SAN (FC, iSCSI, NVMe). Sélectionnez la procédure spécifique au protocole appropriée pour configurer le stockage partagé de votre cluster Proxmox VE.' 
---
= Découvrez les protocoles de stockage pour Proxmox VE avec NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Provisionnez le stockage ONTAP pour l'environnement virtuel Proxmox (VE) en utilisant les protocoles NAS (NFS, SMB) et les protocoles SAN (FC, iSCSI, NVMe). Sélectionnez la procédure spécifique au protocole appropriée pour configurer le stockage partagé de votre cluster Proxmox VE.

Assurez-vous que les hôtes Proxmox VE disposent d'interfaces FC, Ethernet ou autres interfaces prises en charge, câblées à des commutateurs permettant la communication avec les interfaces logiques ONTAP . Vérifiez toujours le https://mysupport.netapp.com/matrix/#welcome["Outil de matrice d'interopérabilité"] pour les configurations prises en charge. Les scénarios d'exemple sont créés en supposant que deux cartes d'interface réseau haut débit sont disponibles sur chaque hôte Proxmox VE et sont connectées entre elles pour créer des interfaces agrégées pour la tolérance aux pannes et les performances. Les mêmes connexions montantes sont utilisées pour tout le trafic réseau, y compris la gestion des hôtes, le trafic des machines virtuelles/conteneurs et l'accès au stockage. Lorsque davantage d'interfaces réseau sont disponibles, envisagez de séparer le trafic de stockage des autres types de trafic.

Pour plus d'informations sur l'architecture de stockage ONTAP et les types de stockage pris en charge, consultez link:proxmox-ontap-architecture.html["Découvrez l'architecture de stockage ONTAP pour Proxmox VE"] et link:proxmox-storage-types.html["Découvrez les types de stockage pris en charge par Proxmox VE"].


NOTE: Lors de l'utilisation de LVM avec des protocoles SAN (FC, iSCSI, NVMe-oF), le groupe de volumes peut contenir plusieurs LUN ou espaces de noms NVMe. Dans ce cas, tous les LUN ou espaces de noms doivent appartenir au même groupe de cohérence pour garantir l'intégrité des données. Nous ne prenons pas en charge les groupes de volumes qui s'étendent sur plusieurs SVM ONTAP . Chaque groupe de volumes doit être créé à partir de LUN ou d'espaces de noms provenant de la même SVM.



== Choisissez un protocole de stockage

Sélectionnez le protocole qui correspond à votre environnement et à vos exigences :

* link:proxmox-ontap-smb.html["Configurer le stockage SMB/CIFS"] - Configurer les partages de fichiers SMB/CIFS pour Proxmox VE avec prise en charge multicanal pour la tolérance aux pannes et des performances améliorées sur plusieurs connexions réseau.
* link:proxmox-ontap-nfs.html["Configurer le stockage NFS"] - Configurez le stockage NFS pour Proxmox VE avec nConnect ou le trunking de session pour la tolérance aux pannes et l'amélioration des performances grâce à l'utilisation de plusieurs connexions réseau.
* link:proxmox-ontap-fc.html["Configurer LVM avec FC"] - Configurez Logical Volume Manager (LVM) avec Fibre Channel pour un accès au stockage par blocs haute performance et à faible latence sur les hôtes Proxmox VE.
* link:proxmox-ontap-iscsi.html["Configurer LVM avec iSCSI"] - Configurer Logical Volume Manager (LVM) avec iSCSI pour l'accès au stockage par blocs sur les réseaux Ethernet standard avec prise en charge multipath.
* link:proxmox-ontap-nvme-fc.html["Configurer LVM avec NVMe/FC"] - Configurez Logical Volume Manager (LVM) avec NVMe sur Fibre Channel pour un stockage de blocs haute performance utilisant le protocole NVMe moderne.
* link:proxmox-ontap-nvme-tcp.html["Configurer LVM avec NVMe/TCP"] - Configurez Logical Volume Manager (LVM) avec NVMe sur TCP pour un stockage de blocs haute performance sur les réseaux Ethernet standard en utilisant le protocole NVMe moderne.

