= Cas d'utilisation
:allow-uri-read: 


Cette migration permet une intégration transparente, une meilleure protection des données et une plus grande flexibilité dans la gestion des environnements virtualisés, garantissant une transition en douceur avec un temps d'arrêt minimal.



== Cas d'utilisation

Il existe de nombreuses options de migration en termes de source et de destination lorsque l'on envisage de migrer vers des magasins de données basés sur ONTAP .

* Migration de systèmes de stockage tiers (y compris vSAN) vers des banques de données ONTAP .
* Migration de machines virtuelles dans le même cluster vSphere
* Migration de machines virtuelles sur plusieurs clusters vSphere
* Migration de machines virtuelles entre serveurs vCenter dans le même domaine SSO
* Migration de machines virtuelles entre serveurs vCenter dans différents domaines SSO
* Migration de machines virtuelles entre différents centres de données
* Migration de systèmes de stockage tiers (y compris vSAN) vers des banques de données ONTAP .
* Migration de machines virtuelles dans un environnement cloud hybride

