---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-mgmt-supp-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS sur FC comme stockage supplémentaire pour les domaines de charge de travail et de gestion VI à l'aide des outils ONTAP pour VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans ce scénario, nous allons démontrer comment déployer une banque de données VMFS avec un backend Fibre Channel (FC) pour les domaines de gestion et de charge de travail à l'aide des outils ONTAP .



== Avantages de Fibre Channel

*Hautes performances :* FC offre des taux de transfert de données à haut débit, ce qui le rend idéal pour les applications nécessitant un accès rapide et fiable à de grandes quantités de données.

*Faible latence :* très faible latence, ce qui est crucial pour les applications sensibles aux performances telles que les bases de données et les environnements virtualisés.

*Fiabilité :* les réseaux FC sont connus pour leur robustesse et leur fiabilité, avec des fonctionnalités telles que la redondance intégrée et la correction d'erreurs.

*Bande passante dédiée :* FC fournit une bande passante dédiée au trafic de stockage, réduisant ainsi le risque de congestion du réseau.

Pour plus d'informations sur l'utilisation de Fibre Channel avec les systèmes de stockage NetApp , reportez-vous à https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Provisionnement SAN avec FC"] .



== Aperçu du scénario

Le magasin de données supplémentaire VCF est fourni dans le cadre des opérations du jour 2 à l'aide de vCenter.  Ce scénario couvre les étapes de haut niveau suivantes :

* Déploiement des outils ONTAP sur le domaine de gestion
* Enregistrer les serveurs vCenter de charge de travail VI dans les outils ONTAP
* Définir le backend de stockage sur le plug-in d'outils ONTAP pour VMware vSphere
* Provisionner VMFS sur le transport FC




== Prérequis

Ce scénario nécessite les composants et configurations suivants :

* Un système de stockage ONTAP avec des ports FC connectés à des commutateurs FC.
* SVM créé avec FC lifs.
* vSphere avec HBA FC connectés aux commutateurs FC.
* Le zonage initiateur-cible unique est configuré sur les commutateurs FC.
+

NOTE: Utilisez l'interface logique SVM FC dans la configuration de zone plutôt que les ports FC physiques sur les systèmes ONTAP .



NetApp recommande le multipath pour les LUN FC.

Pour obtenir des informations complètes sur la configuration de Fibre Channel sur les systèmes de stockage ONTAP , reportez-vous à https://docs.netapp.com/us-en/ontap/san-management/index.html["Gestion du stockage SAN"] dans la documentation ONTAP 9.

Pour plus d'informations sur l'utilisation de VMFS avec les systèmes de stockage ONTAP , reportez-vous aulink:vmw-vmfs-deploy.html["Guide de déploiement pour VMFS"] .



== Étapes de déploiement pour le domaine de gestion

Pour déployer les outils ONTAP et les utiliser pour créer une banque de données VMFS sur le domaine de gestion VCF, procédez comme suit :

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Déployer les outils ONTAP sur le domaine de gestion"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Définir le backend de stockage à l'aide de l'interface client vSphere"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["Provisionner VMFS sur FC"]




== Étapes de déploiement pour le domaine de charge de travail VI

Pour déployer les outils ONTAP et les utiliser pour créer une banque de données VMFS sur le domaine de charge de travail VCF VI, procédez comme suit :

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Enregistrez la charge de travail VI vCenter pour activer le plug-in vCenter"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Définir le backend de stockage à l'aide de l'interface client vSphere"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["Provisionner VMFS sur FC"]




== Informations Complémentaires

Pour plus d'informations sur la configuration des systèmes de stockage ONTAP , reportez-vous aulink:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour plus d'informations sur la configuration de VCF, reportez-vous àlink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentation de VMware Cloud Foundation"] .



== Démo vidéo de cette solution

.Banque de données VMFS(FC) comme stockage supplémentaire pour le domaine de gestion VCF
video::3135c36f-3a13-4c95-aac9-b2a0001816dc[panopto,width=360]