---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Utiliser une banque de données VMFS basée sur FC sur ONTAP comme stockage principal pour un domaine de charge de travail VI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans ce cas d'utilisation, nous décrivons la procédure de configuration d'une banque de données VMFS Fibre Channel (FC) sur ONTAP comme solution de stockage principale pour un domaine de charge de travail d'infrastructure virtuelle (VI) VMware Cloud Foundation (VCF).  Cette procédure résume les composants requis, les étapes de configuration et le processus de déploiement.



== Avantages de Fibre Channel

*Hautes performances :* FC offre des taux de transfert de données à haut débit, ce qui le rend idéal pour les applications nécessitant un accès rapide et fiable à de grandes quantités de données.

*Faible latence :* très faible latence, ce qui est crucial pour les applications sensibles aux performances telles que les bases de données et les environnements virtualisés.

*Fiabilité :* les réseaux FC sont connus pour leur robustesse et leur fiabilité, avec des fonctionnalités telles que la redondance intégrée et la correction d'erreurs.

*Bande passante dédiée :* FC fournit une bande passante dédiée au trafic de stockage, réduisant ainsi le risque de congestion du réseau.

Pour plus d'informations sur l'utilisation de Fibre Channel avec les systèmes de stockage NetApp , reportez-vous à https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Provisionnement SAN avec FC"] .



== Aperçu du scénario

Ce scénario couvre les étapes de haut niveau suivantes :

* Créez une machine virtuelle de stockage (SVM) avec des interfaces logiques (LIF) pour le trafic FC.
* Collectez les informations WWPN des hôtes à déployer et créez des groupes d'initiateurs correspondants sur le système de stockage ONTAP .
* Créez un volume FC sur le système de stockage ONTAP .
* Mapper les groupes d'initiateurs pour créer un volume FC
* Utilisez le zonage initiateur-cible unique sur les commutateurs FC.  Créez une zone pour chaque initiateur (zone d'initiateur unique).
+
** Pour chaque zone, incluez une cible qui est l'interface logique ONTAP FC (WWPN) pour les SVM.  Il doit y avoir au moins deux interfaces logiques par nœud et par SVM.  N'utilisez pas le WWPN des ports physiques.


* Créez un pool réseau pour le trafic vMotion dans SDDC Manager.
* Hôtes de commission dans VCF pour une utilisation dans un domaine de charge de travail VI.
* Déployez un domaine de charge de travail VI dans VCF à l’aide d’une banque de données FC comme stockage principal.



NOTE: Cette solution est applicable aux plates-formes ONTAP prenant en charge le stockage NFS, notamment NetApp AFF et FAS.



== Prérequis

Les composants et configurations suivants sont utilisés dans ce scénario :

* Un système de stockage ONTAP AFF ou ASA avec des ports FC connectés à des commutateurs FC.
* SVM créé avec FC lifs.
* vSphere avec HBA FC connectés aux commutateurs FC.
* Le zonage initiateur-cible unique est configuré sur les commutateurs FC.



NOTE: NetApp recommande le multipath pour les LUN FC.



== Étapes de déploiement



=== Domaine de gestion - Cluster par défaut

Le stockage principal FC sur le cluster initial n'est pris en charge qu'avec l'outil d'importation Brownfield VCF.  Si VCF est déployé avec l'outil cloudbuilder (jusqu'à la version 5.2.x), seul VSAN est pris en charge.  Référer https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["conversion de l'environnement vSphere existant en domaine de gestion"] pour plus d'infos.



=== Domaine de gestion - Cluster supplémentaire

Le cluster vSphere supplémentaire sur le domaine de gestion peut être déployé avec les options suivantes : * Avoir un cluster supplémentaire dans l'environnement vSphere et utiliser l'outil d'importation Brownfield VCF pour convertir l'environnement vSphere en domaine de gestion. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["ONTAP tools for VMware vSphere"] , https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Gestionnaire de système ou API ONTAP"] peut être utilisé pour déployer la banque de données VMFS sur un cluster vSphere. * Utilisez l'API SDDC pour déployer un cluster supplémentaire. Les hôtes vSphere doivent avoir le magasin de données VMFS configuré. Utiliser https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Gestionnaire de système ou API ONTAP"] pour déployer le LUN sur les hôtes vSphere. * Utilisez l’interface utilisateur de SDDC Manager pour déployer un cluster supplémentaire. Mais cette option crée uniquement une banque de données VSAN jusqu'à la version 5.2.x.



=== Domaine de charge de travail VI - Cluster par défaut

Une fois le domaine de gestion opérationnel, le domaine de charge de travail VI peut être créé :

* Utilisation de l'interface utilisateur de SDDC Manager.  Les hôtes vSphere doivent avoir le magasin de données VMFS configuré.  Utilisez System Manager ou l’API ONTAP pour déployer le LUN sur les hôtes vSphere.
* Importez un environnement vSphere existant en tant que nouveau domaine de charge de travail VI.  Les ONTAP tools for VMware vSphere, System Manager ou ONTAP API peuvent être utilisés pour déployer la banque de données VMFS sur un cluster vSphere.




=== Domaine de charge de travail VI - Cluster supplémentaire

Une fois la charge de travail VI opérationnelle, des clusters supplémentaires peuvent être déployés avec VMFS sur FC LUN à l'aide des options suivantes.

* Clusters supplémentaires dans l'environnement vSphere importés à l'aide de l'outil d'importation Brownfield VCF.  Les ONTAP tools for VMware vSphere, System Manager ou ONTAP API peuvent être utilisés pour déployer la banque de données VMFS sur un cluster vSphere.
* Utilisation de l’interface utilisateur ou de l’API SDDC Manager pour déployer un cluster supplémentaire.  Les hôtes vSphere doivent avoir le magasin de données VMFS configuré.  Utilisez System Manager ou l’API ONTAP pour déployer le LUN sur les hôtes vSphere.




== Informations Complémentaires

Pour plus d'informations sur la configuration des systèmes de stockage ONTAP , reportez-vous aulink:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour plus d'informations sur la configuration de VCF, reportez-vous àlink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentation de VMware Cloud Foundation"] .
