---
sidebar: sidebar 
permalink: vmware/vmw-demos-videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, NetApp Copy and Sync, NetApp Backup and Recovery, FabricPool, ONTAP 
summary: Cette page fournit une introduction aux vidéos et tutoriels. 
---
= Regardez des vidéos et des démonstrations sur la virtualisation avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Regardez des vidéos et des démonstrations qui expliquent les fonctionnalités importantes des solutions de cloud hybride, de virtualisation et de conteneurs.  Découvrez comment utiliser les outils NetApp ONTAP tools for VMware vSphere, le SnapCenter Plug-in for VMware vSphere, la protection des données 3-2-1 et comment NetApp fonctionne avec AWS et Azure.  Obtenez des conseils utiles pour configurer et gérer ces technologies.

.Outils NetApp ONTAP pour VMware vSphere
[%collapsible%open]
====
.Outils ONTAP pour VMware - Présentation
video::e8071955-f6f1-45a0-a868-b12a010bba44[panopto]
.Provisionnement de la banque de données VMware iSCSI avec ONTAP
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.Provisionnement de la banque de données VMware NFS avec ONTAP
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.SnapCenter Plug-in for VMware vSphere
[%collapsible%open]
====
Le logiciel NetApp SnapCenter software est une plate-forme d'entreprise facile à utiliser pour coordonner et gérer en toute sécurité la protection des données entre les applications, les bases de données et les systèmes de fichiers.

Le SnapCenter Plug-in for VMware vSphere vous permet d'effectuer des opérations de sauvegarde, de restauration et de connexion pour les machines virtuelles et des opérations de sauvegarde et de montage pour les banques de données enregistrées auprès de SnapCenter directement dans VMware vCenter.

Pour plus d'informations sur le SnapCenter Plug-in for VMware vSphere-in NetApp SnapCenter pour VMware vSphere, consultez lelink:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Présentation du SnapCenter Plug-in for VMware vSphere-in NetApp SnapCenter pour VMware vSphere"] .

.SnapCenter Plug-in for VMware vSphere : conditions préalables à la solution
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - Déploiement
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - Workflow de sauvegarde
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere – Workflow de restauration
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.SnapCenter - Flux de travail de restauration SQL
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.Solutions de protection des données 3-2-1
[%collapsible%open]
====
Les solutions de protection des données 3-2-1 combinent des sauvegardes primaires et secondaires sur site, utilisant la technologie SnapMirror , avec des copies répliquées sur le stockage d'objets utilisant NetApp Backup and Recovery.

.Protection des données 3-2-1 pour les datastores VMFS avec le SnapCenter Plug-in for VMware vSphere et NetApp Backup and Recovery pour machines virtuelles
video::7c21f3fc-4025-4d8f-b54c-b0e001504c76[panopto,width=360]
====
.VMware Cloud sur AWS avec AWS FSx ONTAP
[%collapsible%open]
====
.Stockage invité Windows connecté avec FSx ONTAP à l'aide d'iSCSI
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Stockage invité Linux connecté avec FSx ONTAP utilisant NFS
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.Économies TCO VMware Cloud sur AWS avec Amazon FSx ONTAP
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.Banque de données supplémentaire VMware Cloud sur AWS avec Amazon FSx ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.Déploiement et configuration de VMware HCX pour VMC
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.Démonstration de migration vMotion avec VMware HCX pour VMC et FSx ONTAP
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.Démonstration de migration à froid avec VMware HCX pour VMC et FSx ONTAP
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.Azure VMware Services sur Azure avec Azure NetApp Files (ANF)
[%collapsible%open]
====
.Présentation du magasin de données supplémentaire Azure VMware Solution avec Azure NetApp Files
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Solution Azure VMware DR avec Cloud Volumes ONTAP, SnapCenter et JetStream
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.Démonstration de migration à froid avec VMware HCX pour AVS et ANF
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.Démonstration de vMotion avec VMware HCX pour AVS et ANF
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.Démonstration de migration en masse avec VMware HCX pour AVS et ANF
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.VMware Cloud Foundation avec NetApp ONTAP
[%collapsible%open]
====
.Banques de données NFS comme stockage principal pour les domaines de charge de travail VCF
video::9b66ac8d-d2b1-4ac4-a33c-b16900f67df6[panopto]
.Banques de données iSCSI comme stockage supplémentaire pour les domaines de gestion VCF
video::1d0e1af1-40ae-483a-be6f-b156015507cc[panopto]
====
.Cloud Insights NetApp
[%collapsible%open]
====
NetApp Cloud Insights est une plate-forme complète de surveillance et d'analyse conçue pour fournir une visibilité et un contrôle sur votre infrastructure sur site et cloud.

.NetApp Cloud Insights : Observabilité pour les centres de données modernes
video::1e4da521-3104-4d51-8cde-b0e001502d3d[panopto,width=360]
====