---
sidebar: sidebar 
permalink: vmware/vmw-vcf-provision.html 
keywords: vmware, vcf, provision, principal, storage 
summary:  
---
= Provisionner un environnement VCF avec ONTAP comme solution de stockage principale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp ONTAP storage est une solution de stockage principale idéale pour les domaines de gestion et de charge de travail de VMware Cloud Foundation (VCF). ONTAP offre des performances élevées, une grande évolutivité, un logiciel de gestion des données avancé et une intégration transparente pour améliorer l'efficacité opérationnelle et la protection des données.

Veuillez vous référer aux solutions suivantes pour les détails techniques de la mise en service d'un environnement VCF dans le domaine approprié et avec le protocole approprié.

* link:vmw-vcf-mgmt-principal-fc.html["Domaine de gestion avec FC"]
* link:vmw-vcf-mgmt-principal-nfs.html["Domaine de gestion avec NFS"]
* link:vmw-vcf-viwld-principal-fc.html["Domaine de workload avec FC"]
* link:vmw-vcf-viwld-principal-nfs.html["Domaine de workload avec NFS"]

