---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: 'Examinez les exigences relatives à la convergence d"un cluster vSphere avec des datastores NFS NetApp ONTAP vers un domaine de gestion VMware Cloud Foundation.' 
---
= Exigences de déploiement pour la convergence d'une instance de serveur vCenter vers un domaine de gestion VCF à l'aide de datastores NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Examinez les exigences relatives à la convergence d'un cluster vSphere avec des datastores NFS NetApp ONTAP vers un domaine de gestion VMware Cloud Foundation.

Le processus de convergence nécessite un système de stockage AFF ou AFX, des SVM et des LIF pour le trafic NFS, des VLAN NFS sur les commutateurs, un cluster vSphere avec des hôtes vSphere et vCenter, ainsi qu’un segment de réseau dédié pour vMotion.



[[infrastructure-requirements]]
== Exigences en matière d'infrastructure

Assurez-vous que les composants et configurations suivants sont en place.

* NetApp AFF ou AFX système de stockage avec une machine virtuelle de stockage (SVM) configurée pour autoriser le trafic NFS.
* Interface logique (LIF) créée sur le réseau IP pour transporter le trafic NFS et associée au SVM.
* Un cluster vSphere avec au moins 2 hôtes vSphere et un appliance vCenter colocalisé sur le cluster.
* Groupe de ports distribués configuré pour le trafic de stockage vMotion et NFS sur les VLAN ou segments de réseau établis à cet effet.
* Outil d'installation VCF pour la convergence de vCenter vers le domaine de gestion VCF.
* Prérequis pour les outils ONTAP .
+
Pour obtenir des informations complètes sur les prérequis pour les outils ONTAP , reportez-vous à https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["Prérequis pour les ONTAP tools for VMware vSphere"] .

+
Les ONTAP tools for VMware vSphere peuvent être installés dans des configurations HA ou non HA.





[[additional-resources]]
== Ressources supplémentaires

* Pour plus d'informations sur le stockage pris en charge et d'autres considérations relatives à la convergence de vSphere vers VCF, veuillez consulter https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-and-not-supported-configurations.html["Configurations prises en charge et non prises en charge pour la convergence vers VCF"].
* Pour plus d'informations sur la configuration des systèmes de stockage ONTAP , reportez-vous aulink:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] .
* Pour plus d'informations sur la configuration de VCF, reportez-vous au link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentation VMware Cloud Foundation 9.1"].




[[whats-next]]
== Quelle est la prochaine étape ?

Après avoir examiné les exigences de déploiement,link:vmw-vcf-mgmt-nfs-deploy.html["déployer les outils ONTAP et provisionner la banque de données NFS"] .
