---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-otv.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= En savoir plus sur la gestion des machines virtuelles à l'aide des ONTAP tools for VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les ONTAP tools for VMware vSphere rationalisent la gestion du cycle de vie des machines virtuelles utilisant le stockage NetApp .  Les administrateurs peuvent gérer le stockage directement depuis vCenter Server, simplifiant ainsi les opérations et améliorant l'évolutivité.  Les composants clés tels que la console de stockage virtuelle (VSC), le fournisseur VASA et l'adaptateur de réplication de stockage (SRA) optimisent le provisionnement, la surveillance des performances et la reprise après sinistre.



== Introduction

Il permet aux administrateurs de gérer directement le stockage au sein du vCenter Server et de simplifier la gestion du stockage et des données pour les environnements VMware.  L'outil de plug-in VMware vSphere Client est conçu pour intégrer la fonctionnalité de plug-in dans vSphere Client sans avoir besoin de l'exécuter dans vCenter Server.  Cela permet l'isolation des plug-ins et la mise à l'échelle des plug-ins qui fonctionnent dans de grands environnements vSphere.



== Composants des outils ONTAP

* *Console de stockage virtuelle (VSC)* La VSC inclut l'interface intégrée au client vSphere où vous pouvez ajouter des contrôleurs de stockage, provisionner des banques de données, surveiller les performances des banques de données et afficher et mettre à jour les paramètres de l'hôte ESXi.
* *Fournisseur VASA* Le fournisseur VMware vSphere APIs for Storage Awareness (VASA) pour ONTAP envoie des informations sur le stockage utilisé par VMware vSphere au serveur vCenter, permettant ainsi le provisionnement des banques de données VMware Virtual Volumes (vVols), la création et l'utilisation de profils de capacité de stockage, la vérification de la conformité et la surveillance des performances.
* *Adaptateur de réplication de stockage (SRA)* Lorsqu'il est activé et utilisé avec VMware Site Recovery Manager (SRM), SRA facilite la récupération des banques de données et des machines virtuelles vCenter Server en cas de panne, permettant la configuration de sites protégés et de sites de récupération pour la reprise après sinistre.


Pour plus d'informations sur les outils NetApp ONTAP pour VMware, consultez https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["Documentation des ONTAP tools for VMware vSphere"] .
