---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-supp-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Ajoutez une banque de données VMFS basée sur FC comme stockage supplémentaire aux domaines de charge de travail VI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans ce cas d'utilisation, nous décrivons la procédure de configuration d'une banque de données VMFS à l'aide de Fibre Channel (FC) comme stockage supplémentaire pour un domaine de charge de travail d'infrastructure virtuelle (VI) VMware Cloud Foundation (VCF).  Cette procédure résume le déploiement d' ONTAP Tools pour VMware vSphere, l'enregistrement du serveur vCenter de charge de travail VI, la définition du backend de stockage et le provisionnement du magasin de données FC.



== Avantages de Fibre Channel

*Hautes performances :* FC offre des taux de transfert de données à haut débit, ce qui le rend idéal pour les applications nécessitant un accès rapide et fiable à de grandes quantités de données.

*Faible latence :* très faible latence, ce qui est crucial pour les applications sensibles aux performances telles que les bases de données et les environnements virtualisés.

*Fiabilité :* les réseaux FC sont connus pour leur robustesse et leur fiabilité, avec des fonctionnalités telles que la redondance intégrée et la correction d'erreurs.

*Bande passante dédiée :* FC fournit une bande passante dédiée au trafic de stockage, réduisant ainsi le risque de congestion du réseau.

Pour plus d'informations sur l'utilisation de Fibre Channel avec les systèmes de stockage NetApp , reportez-vous à https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Provisionnement SAN avec FC"] .



== Aperçu du scénario

Le magasin de données supplémentaire VCF est fourni dans le cadre des opérations du jour 2 à l'aide de vCenter.  Ce scénario couvre les étapes de haut niveau suivantes :

* Déploiement des outils ONTAP sur le domaine de gestion
* Enregistrer les serveurs vCenter de charge de travail VI dans les outils ONTAP
* Définir le backend de stockage sur le plug-in d'outils ONTAP pour VMware vSphere
* Provisionner VMFS sur le transport FC




== Prérequis

Ce scénario nécessite les composants et configurations suivants :

* Un système de stockage ONTAP AFF ou ASA avec des ports FC connectés à des commutateurs FC.
* SVM créé avec FC lifs.
* vSphere avec HBA FC connectés aux commutateurs FC.
* Le zonage initiateur-cible unique est configuré sur les commutateurs FC.
+

NOTE: Utilisez l'interface logique SVM FC dans la configuration de zone plutôt que les ports FC physiques sur les systèmes ONTAP .



NetApp recommande le multipath pour les LUN FC.

Pour obtenir des informations complètes sur la configuration du canal de fibre sur les systèmes de stockage ONTAP , reportez-vous à https://docs.netapp.com/us-en/ontap/san-management/index.html["Gestion du stockage SAN"] dans la documentation ONTAP 9.

Pour plus d'informations sur l'utilisation de VMFS avec les systèmes de stockage ONTAP , reportez-vous aulink:vmw-vmfs-deploy.html["Guide de déploiement pour VMFS"] .



== Étapes de déploiement pour le domaine de charge de travail VI

Pour déployer les outils ONTAP et les utiliser pour créer une banque de données VMFS sur le domaine de charge de travail VCF VI, procédez comme suit :

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Enregistrez la charge de travail VI vCenter pour activer le plug-in vCenter"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Définir le backend de stockage à l'aide de l'interface client vSphere"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["Provisionner VMFS sur FC"]




== Informations Complémentaires

Pour plus d'informations sur la configuration des systèmes de stockage ONTAP , reportez-vous aulink:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour plus d'informations sur la configuration de VCF, reportez-vous àlink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentation de VMware Cloud Foundation"] .



== Démo vidéo de cette solution

.Banque de données VMFS(FC) comme stockage supplémentaire pour le domaine de gestion VCF
video::3135c36f-3a13-4c95-aac9-b2a0001816dc[panopto,width=360]