---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-nfs.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, nfs 
summary:  
---
= Utiliser une banque de données NFS sur ONTAP comme stockage principal pour le domaine de gestion VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce cas d'utilisation décrit la procédure de création d'un datastore NFS sur ONTAP en tant que stockage principal pour le domaine de gestion VMware Cloud Foundation (VCF). Cette procédure récapitule les composants requis, les étapes de configuration et le processus de déploiement.



[[introduction]]
== Introduction

Le cas échéant, nous nous référerons à la documentation externe pour les étapes à effectuer dans vCenter, et nous ferons référence à celles qui sont spécifiques à la partie configuration du stockage.

Si une banque de données NFS 4.1 doit être utilisée pour le stockage principal ou si vous convertissez un environnement vSphere existant basé sur NFS avec ONTAP, reportez-vous à link:vmw-vcf-mgmt-nfs.html["Converger l’environnement vSphere (datastore NFS) vers le domaine de gestion VCF"].


NOTE: La version 5.2 de VCF a introduit la possibilité de convertir un environnement vSphere 8 existant en un domaine de gestion VCF ou de l’importer en tant que domaine de charge de travail VCF VI. Avant cette version, VMware vSAN était la seule option de stockage principal pour le domaine de gestion VCF. Il est préférable de déployer les machines virtuelles du contrôleur NSX sur une banque de données VMFS basée sur FC ou d’utiliser un double commutateur réseau afin d’éviter un point de défaillance unique. Si ces options ne sont pas disponibles, envisagez d’utiliser vSAN pour héberger ces machines virtuelles.


NOTE: Cette solution est applicable aux plateformes ONTAP prenant en charge le stockage NFS, y compris NetApp AFF, AFX et FAS.



[[prerequisites]]
== Prérequis

Les composants et configurations suivants sont utilisés dans ce scénario :

* Système de stockage NetApp avec une machine virtuelle de stockage (SVM) configurée pour autoriser le trafic NFS.
* L'interface logique (LIF) a été créée sur le réseau IP qui doit transporter le trafic NFS et est associée au SVM.
* Un cluster vSphere avec au moins 2 hôtes vSphere.
* Banque de données NFS montée sur l'un des hôtes vSphere avec le même serveur NFS et le même chemin d'exportation qui sera utilisé pour le domaine de gestion.



NOTE: Lors du déploiement d'un domaine VCF, VCF vérifie la connectivité au serveur NFS. Cette vérification s'effectue via l'adaptateur de gestion sur les hôtes vSphere avant qu'un adaptateur vmkernel supplémentaire ne soit ajouté avec l'adresse IP NFS. Par conséquent, il est nécessaire de s'assurer que soit 1) le réseau de gestion est routable vers le serveur NFS, soit 2) une LIF pour le réseau de gestion a été ajoutée à la SVM hébergeant le volume de la banque de données NFS, afin de garantir que la validation puisse avoir lieu.

* Assurez-vous que l'outil ONTAP NFS VAAI est installé sur l'un des vSphere hôtes pouvant être sélectionné comme modèle pour l'image du cluster.
* Déployez l'outil d'installation VCF.


Pour plus d'informations sur la configuration des systèmes de stockage ONTAP , reportez-vous aulink:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour obtenir des informations sur la configuration de VCF, consultez link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentation de VMware Cloud Foundation"].



[[deployment-steps]]
== Étapes de déploiement



[[management-domain-default-cluster]]
=== Domaine de gestion - Cluster par défaut

L'outil d'installation VCF prend en charge les datastores VMFS sur FC, NFS v3 et vSAN pour le domaine de gestion. Les étapes suivantes décrivent la procédure de déploiement d'un domaine de gestion avec un datastore basé sur NFSv3 sur ONTAP comme stockage principal.


NOTE: Validez ou ajustez la valeur nConnect pour le datastore NFS après le déploiement.

Pour plus d'informations sur l'utilisation d'un environnement vSphere existant, veuillez vous référer à link:vmw-vcf-mgmt-nfs.html["Converger l’environnement vSphere (datastore NFS) vers le domaine de gestion VCF"].



[[management-domain-additional-cluster]]
=== Domaine de gestion - Cluster supplémentaire

Pour étendre le domaine de gestion avec un cluster supplémentaire, reportez-vous à https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Ajouter un cluster SDDC à un domaine VCF"].

À un niveau élevé, les étapes pour ajouter un cluster supplémentaire au domaine de gestion sont les suivantes : * Assurez-vous que les hôtes sont commissionnés et que les pools réseau sont configurés dans vCenter. * Le volume du datastore NFS est provisionné sur le système de stockage ONTAP et exporté vers les hôtes du cluster supplémentaire. * Créez un nouveau cluster SDDC dans le domaine de gestion sur vCenter et suivez l’assistant pour ajouter le cluster supplémentaire au domaine de gestion.



[[additional-information]]
== Informations Complémentaires

Pour plus d'informations sur la configuration des systèmes de stockage ONTAP , reportez-vous aulink:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour obtenir des informations sur la configuration de VCF, consultez link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentation de VMware Cloud Foundation"].
