---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-otv.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= En savoir plus sur la gestion des machines virtuelles à l'aide des ONTAP tools for VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere simplifie la gestion du cycle de vie des VM à l'aide du stockage NetApp. Les administrateurs peuvent gérer le stockage directement à partir de vCenter Server, ce qui simplifie les opérations et améliore l'évolutivité. Des composants clés tels que le plug-in vSphere Client, VASA Provider et Storage Replication Adapter (SRA) optimisent le provisionnement, la surveillance des performances et la reprise d'activité.



[[introduction]]
== Introduction

Il permet aux administrateurs de gérer directement le stockage au sein du vCenter Server et de simplifier la gestion du stockage et des données pour les environnements VMware.  L'outil de plug-in VMware vSphere Client est conçu pour intégrer la fonctionnalité de plug-in dans vSphere Client sans avoir besoin de l'exécuter dans vCenter Server.  Cela permet l'isolation des plug-ins et la mise à l'échelle des plug-ins qui fonctionnent dans de grands environnements vSphere.



[[ontap-tools-components]]
== Composants des outils ONTAP

* *vSphere Client plug-in* Ce plug-in inclut l'interface intégrée au client vSphere dans laquelle vous pouvez ajouter des contrôleurs de stockage, provisionner des datastores, surveiller les performances des datastores, et afficher et mettre à jour les paramètres de l'hôte ESXi. Dans ONTAP tools 9.x, ce composant est appelé Virtual Storage Console (VSC).
* *Fournisseur VASA* Le fournisseur VMware vSphere APIs for Storage Awareness (VASA) pour ONTAP envoie des informations sur le stockage utilisé par VMware vSphere au serveur vCenter, permettant ainsi le provisionnement des banques de données VMware Virtual Volumes (vVols), la création et l'utilisation de profils de capacité de stockage, la vérification de la conformité et la surveillance des performances.
* *Adaptateur de réplication de stockage (SRA)* Lorsqu'il est activé et utilisé avec VMware Site Recovery Manager (SRM), SRA facilite la récupération des banques de données et des machines virtuelles vCenter Server en cas de panne, permettant la configuration de sites protégés et de sites de récupération pour la reprise après sinistre.


Pour plus d'informations, consultez la documentation de ONTAP tools for VMware vSphere correspondant à votre version :

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["Documentation de ONTAP tools for VMware vSphere 10.x"^] (dernière version)
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["Documentation de ONTAP tools for VMware vSphere 9.x"^]

