---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Utiliser une banque de données VMFS basée sur FC sur ONTAP comme stockage principal pour le domaine de gestion VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce cas d'utilisation décrit la procédure de création d'un datastore VMFS basé sur FC sur ONTAP comme stockage principal pour le domaine de gestion VMware Cloud Foundation (VCF). Cette procédure récapitule les composants, les configurations et les étapes de déploiement nécessaires.



[[introduction]]
== Introduction

Le cas échéant, nous nous référerons à la documentation externe pour les étapes à effectuer dans vCenter, et nous ferons référence à celles qui sont spécifiques à la partie configuration du stockage.

Pour obtenir des informations sur la conversion d’un datastore VMFS existant (y compris iSCSI et NVMe-oF) dans un environnement vSphere avec ONTAP, reportez-vous à link:vmw-vcf-mgmt-vmfs.html["Converger l’environnement vSphere (datastore VMFS) vers le domaine de gestion VCF"].


NOTE: La version 5.2 de VCF a introduit la possibilité de convertir un environnement vSphere 8 existant en un domaine de gestion VCF ou de l’importer en tant que domaine de charge de travail VCF VI. Avant cette version, VMware vSAN était la seule option de stockage principal pour le domaine de gestion VCF. Il est préférable de déployer les machines virtuelles du contrôleur NSX sur une banque de données VMFS basée sur FC ou d’utiliser un double commutateur réseau afin d’éviter un point de défaillance unique. Si ces options ne sont pas disponibles, envisagez d’utiliser vSAN pour héberger ces machines virtuelles.


NOTE: Cette solution est applicable aux plates-formes ONTAP prenant en charge le stockage FC, notamment NetApp ASA, AFF et FAS.



[[prerequisites]]
== Prérequis

Les composants et configurations suivants sont utilisés dans ce scénario :

* Système de stockage NetApp avec une machine virtuelle de stockage (SVM) configurée pour autoriser le trafic FC.
* Des interfaces logiques (LIF) ont été créées sur la structure FC qui doit transporter le trafic FC et est associée au SVM.
* Le zonage a été configuré pour utiliser un zonage à initiateur unique-cible sur les commutateurs FC pour les HBA hôtes et les cibles de stockage.
* Créez un datastore VMFS (avec LUN FC) sur l’un des hôtes vSphere du cluster.


Pour plus d'informations sur la configuration des systèmes de stockage ONTAP , reportez-vous aulink:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour obtenir des informations sur la configuration de VCF, consultez link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentation de VMware Cloud Foundation"].



[[deployment-steps]]
== Étapes de déploiement



[[management-domain-default-cluster]]
=== Domaine de gestion - Cluster par défaut

L'outil d'installation VCF prend en charge les datastores VMFS sur FC, NFS v3 et vSAN pour le domaine de gestion. Les étapes suivantes décrivent la procédure de déploiement d'un domaine de gestion avec un datastore VMFS basé sur FC sur ONTAP comme stockage principal.

Pour plus d'informations sur l'utilisation d'un environnement vSphere existant, veuillez vous référer à link:vmw-vcf-mgmt-vmfs.html["Converger l’environnement vSphere (datastore VMFS) vers le domaine de gestion VCF"].



[[management-domain-additional-cluster]]
=== Domaine de gestion - Cluster supplémentaire

Pour étendre le domaine de gestion avec un cluster supplémentaire, reportez-vous à https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Ajouter un cluster SDDC à un domaine VCF"].

À un niveau élevé, les étapes pour ajouter un cluster supplémentaire au domaine de gestion sont les suivantes : * Assurez-vous que les hôtes sont commissionnés et que les pools réseau sont configurés dans vCenter. * Un LUN est provisionné sur le système de stockage ONTAP et présenté aux hôtes du cluster supplémentaire. * Créez un nouveau cluster SDDC dans le domaine de gestion sur vCenter et suivez l’assistant pour ajouter le cluster supplémentaire au domaine de gestion.



[[reference-video]]
== Vidéo de référence

.Datastore principal avec FC
video::9c51101c-292b-41ef-8dd5-b4cf0131dd62[panopto,width=360]


[[additional-information]]
== Informations Complémentaires

Pour plus d'informations sur la configuration des systèmes de stockage ONTAP , reportez-vous aulink:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour obtenir des informations sur la configuration de VCF, consultez link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentation de VMware Cloud Foundation"].
