---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Utilisez un datastore VMFS basé sur FC sur ONTAP comme stockage principal pour un domaine de charge de travail VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce cas d'utilisation décrit la procédure de configuration d'un datastore VMFS Fibre Channel (FC) sur ONTAP en tant que solution de stockage principale pour un domaine de charge de travail VMware Cloud Foundation (VCF). Cette procédure récapitule les composants requis, les étapes de configuration et le processus de déploiement.



[[benefits-of-fibre-channel]]
== Avantages de Fibre Channel

*Hautes performances :* FC offre des taux de transfert de données à haut débit, ce qui le rend idéal pour les applications nécessitant un accès rapide et fiable à de grandes quantités de données.

*Faible latence :* très faible latence, ce qui est crucial pour les applications sensibles aux performances telles que les bases de données et les environnements virtualisés.

*Fiabilité :* les réseaux FC sont connus pour leur robustesse et leur fiabilité, avec des fonctionnalités telles que la redondance intégrée et la correction d'erreurs.

*Bande passante dédiée :* FC fournit une bande passante dédiée au trafic de stockage, réduisant ainsi le risque de congestion du réseau.

Pour plus d'informations sur l'utilisation de Fibre Channel avec les systèmes de stockage NetApp , reportez-vous à https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Provisionnement SAN avec FC"] .



[[scenario-overview]]
== Aperçu du scénario

Ce scénario couvre les étapes de haut niveau suivantes :

* Créez une machine virtuelle de stockage (SVM) avec des interfaces logiques (LIF) pour le trafic FC.
* Collectez les informations WWPN des hôtes à déployer et créez des groupes d'initiateurs correspondants sur le système de stockage ONTAP .
* Créez un volume FC sur le système de stockage ONTAP .
* Mappez les groupes d'initiateurs au volume FC créé.
* Utilisez le zonage initiateur-cible unique sur les commutateurs FC.  Créez une zone pour chaque initiateur (zone d'initiateur unique).
+
** Pour chaque zone, incluez une cible qui est l'interface logique ONTAP FC (WWPN) pour les SVM.  Il doit y avoir au moins deux interfaces logiques par nœud et par SVM.  N'utilisez pas le WWPN des ports physiques.


* Créez un pool de réseau pour le trafic vMotion dans vCenter.
* Mettre en service des hôtes dans vCenter pour une utilisation dans un Workload Domain.
* Déployez un domaine de charge de travail dans VCF Ops en utilisant un datastore VMFS sur FC comme stockage principal.



NOTE: Cette solution est applicable aux plateformes ONTAP prenant en charge le stockage FC, notamment NetApp ASAr2, AFF et FAS.



[[prerequisites]]
== Prérequis

Les composants et configurations suivants sont utilisés dans ce scénario :

* Un système de stockage ONTAP AFF, ASA ou FAS avec des ports FC connectés à des commutateurs FC.
* SVM créé avec FC lifs.
* vSphere avec HBA FC connectés aux commutateurs FC.
* Le zonage initiateur-cible unique est configuré sur les commutateurs FC.
* Assurez-vous que la stratégie de multipathing SVM est définie sur actif-actif.



NOTE: NetApp recommande le multipath pour les LUN FC.



[[deployment-steps]]
== Étapes de déploiement



[[vcf-workload-domain-default-cluster]]
=== Domaine de charge de travail VCF - Cluster par défaut

Une fois le domaine de gestion opérationnel, le domaine de charge de travail VCF peut être créé :

* Utilisez l'interface utilisateur VCF Ops. Les hôtes vSphere sont mis en service dans vCenter et le pool réseau est configuré. Utilisez System Manager ou l'API ONTAP pour déployer une LUN sur les hôtes vSphere.
* Importez un environnement vSphere existant en tant que nouveau domaine de charge de travail. Les ONTAP tools for VMware vSphere, System Manager ou l'API ONTAP peuvent être utilisés pour déployer la banque de données VMFS sur le cluster vSphere.




[[vcf-workload-domain-additional-cluster]]
=== Domaine de charge de travail VCF - Cluster supplémentaire

Pour étendre le domaine de charge de travail avec un cluster supplémentaire, reportez-vous à https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Ajouter un cluster SDDC à un domaine VCF"].

Voici les étapes principales pour ajouter un cluster supplémentaire au domaine de charge de travail : * Assurez-vous que les hôtes sont commissionnés et que les pools réseau sont configurés dans vCenter. * Un LUN est provisionné sur le système de stockage ONTAP et présenté aux hôtes du cluster supplémentaire. * Créez un nouveau cluster SDDC dans le domaine de charge de travail sur vCenter et suivez l’assistant pour ajouter le cluster supplémentaire au domaine de charge de travail.



[[additional-information]]
== Informations Complémentaires

Pour plus d'informations sur la configuration des systèmes de stockage ONTAP , reportez-vous aulink:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour obtenir des informations sur la configuration de VCF, consultez link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentation de VMware Cloud Foundation"].
