---
sidebar: sidebar 
permalink: vmware/vmware-smbc-cvt-smas.html 
keywords: NetApp Solutions, vMSC, Metro Storage Cluster, SnapMirror active sync, Business Continuity, SMBC, ONTAP Tools, AFD, SCV, iSCSI, backup, restore 
summary:  
---
= Convertir SM Active Sync d'asymétrique en symétrique actif/actif avec VMware vSphere Metro Storage Cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cet article détaille comment convertir la synchronisation active SnapMirror d'asymétrique en symétrique actif/actif avec VMware vSphere Metro Storage Cluster (VMSC).



== Aperçu

link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/["Synchronisation active NetApp Snapmirror (synchronisation active SM)"]est une solution robuste permettant d'atteindre un objectif de temps de récupération (RTO) et un objectif de point de récupération (RPO) nuls dans un environnement virtualisé.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html["Cluster de stockage VMware vSphere Metro (vMSC)"]est une solution de cluster étendue sur différents domaines de pannes et permet aux machines virtuelles (VM) d'être distribuées sur deux sites géographiquement séparés, offrant une disponibilité continue même en cas de panne d'un site.

La combinaison de vMSC avec SM Active Sync garantit la cohérence des données et des capacités de basculement immédiat entre deux sites.  Cette configuration est particulièrement cruciale pour les applications critiques où toute perte de données ou tout temps d’arrêt est inacceptable.

SM Active Sync, anciennement connu sous le nom de SnapMirror Business Continuity (SMBC), permet aux services d'entreprise de continuer à fonctionner même en cas de panne complète du site, en prenant en charge le basculement transparent des applications à l'aide d'une copie secondaire.  À partir d' ONTAP 9.15.1, SM Active Sync prend en charge une capacité symétrique active/active.  La fonction symétrique active/active permet des opérations d'E/S de lecture et d'écriture à partir des deux copies d'un LUN protégé avec une réplication synchrone bidirectionnelle afin que les deux copies de LUN puissent servir les opérations d'E/S localement.

Ce document vous montre les étapes à suivre pour convertir une synchronisation active SM asymétrique active/active en synchronisation active SM symétrique active/active dans un environnement de cluster extensible VMware, en d'autres termes, convertit une synchronisation active SM d'une politique de basculement automatisé en politique de basculement-duplex automatisé.  Pour plus de détails sur la configuration du vMSC avec SnapMirror Active Sync (SM-as) à l'aide de System Manager et des outils ONTAP , consultezlink:vmw-vmsc-with-smas.html["Cluster de stockage VMware vSphere Metro avec synchronisation active SnapMirror"] .



== Prérequis

* Systèmes de stockage NetApp : assurez-vous de disposer de deux clusters de stockage NetApp (source et destination) avec des licences Snapmirror.
* Connectivité réseau : vérifiez la connectivité réseau à faible latence entre les systèmes source et de destination.
* Appairage de cluster et de SVM : configurez l'appairage de cluster et l'appairage de machine virtuelle de stockage (SVM) entre les clusters source et de destination.
* Version ONTAP : assurez-vous que les deux clusters exécutent une version d’ ONTAP qui prend en charge la réplication synchrone.  Pour la synchronisation active SM, ONTAP 9.15.1 et versions ultérieures sont requis.
* Infrastructure VMware vMSC : un cluster étendu permet aux sous-systèmes de s'étendre sur plusieurs zones géographiques, présentant un ensemble de ressources d'infrastructure de base unique et commun au cluster vSphere sur les deux sites.  Il étend le réseau et le stockage entre les sites.
* Utilisez les outils ONTAP 10.2 et versions ultérieures pour une utilisation plus facile de NetApp SnapMirror, consultez plus de détailslink:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/release-notes/ontap-tools-9-ontap-tools-10-feature-comparison.html["ONTAP tools for VMware vSphere 10."]
* Une relation synchrone Snapmirror RPO nulle doit exister entre le cluster principal et le cluster secondaire.
* Tous les LUN sur le volume de destination doivent être démappés avant que la relation Snapmirror à RTO zéro puisse être créée.
* Snapmirror Active Sync prend uniquement en charge les protocoles SAN (pas NFS/CIFS).  Assurez-vous qu'aucun constituant du groupe de cohérence n'est monté pour l'accès NAS.




== Étapes pour convertir une synchronisation active SM asymétrique en synchronisation active SM symétrique

Dans l'exemple ci-dessous, selectrz1 est le site principal et selectrz2 est le site secondaire.

. À partir du site secondaire, effectuez une mise à jour SnapMirror sur la relation existante.
+
....
selectrz2::> snapmirror update -destination-path site2:/cg/CGsite1_dest
....
. Vérifiez que la mise à jour de SnapMirror s'est terminée avec succès.
+
....
selectrz2::> snapmirror show
....
. Mettez en pause chacune des relations synchrones à RPO nul.
+
....
 selectrz2::> snapmirror quiesce -destination-path site2:/cg/CGsite1_dest
....
. Supprimez chacune des relations synchrones RPO zéro.
+
....
selectrz2::> snapmirror delete -destination-path site2:/cg/CGsite1_dest
....
. Libérez la relation source SnapMirror mais conservez les instantanés communs.
+
....
selectrz1::> snapmirror release -relationship-info-only  true -destination-path svm0.1:/cg/CGsite1_dest                                           ".
....
. Créez une relation synchrone SnapMirror à RTO nul avec la stratégie AutomatedFailoverDuplex.
+
....
selectrz2::> snapmirror create -source-path svm0.1:/cg/CGsite1 -destination-path site2:/cg/CGsite1_dest -cg-item-mappings site1lun1:@site1lun1_dest -policy AutomatedFailOverDuplex
....
. Si les hôtes existants sont locaux dans le cluster principal, ajoutez l'hôte au cluster secondaire et établissez la connectivité avec un accès respectif à chaque cluster.
. Sur le site secondaire, supprimez les cartes LUN sur les igroups associés aux hôtes distants.
+
....
selectrz2::> lun mapping delete -vserver svm0 -igroup wlkd01 -path  /vol/wkld01/wkld01
....
. Sur le site principal, modifiez la configuration de l’initiateur pour les hôtes existants afin de définir le chemin proximal des initiateurs sur le cluster local.
+
....
selectrz1::> set -privilege advanced
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1  -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver site1
....
. Ajoutez un nouveau groupe d'hôte et un initiateur pour les nouveaux hôtes et définissez la proximité de l'hôte pour l'affinité de l'hôte avec son site local.  Activez la réplication igroup pour répliquer la configuration et inverser la localité de l'hôte sur le cluster distant.
+
....
selectrz1::*> igroup modify -vserver site1  -igroup smbc2smas -replication-peer svm0.1
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1 -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver svm0.1
....
. Découvrez les chemins sur les hôtes et vérifiez que les hôtes disposent d'un chemin actif/optimisé vers le LUN de stockage à partir du cluster préféré.
. Déployez l’application et répartissez les charges de travail de la machine virtuelle sur les clusters.
. Resynchroniser le groupe de cohérence.
+
....
selectrz2::> snapmirror resync -destination-path site2:/cg/CGsite1_dest
....
. Réanalysez les chemins d'E/S des LUN hôtes pour restaurer tous les chemins vers les LUN.

