---
sidebar: sidebar 
permalink: videos/hybrid-cloud-videos.html 
summary: Vidéos et démonstrations présentant des solutions de virtualisation de cloud hybride avec NetApp 
keywords: hybrid cloud, rosa, fsx ontap, azure vmware, netapp hci, videos, demos 
---
= Regardez des vidéos sur la virtualisation multiCloud hybride avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Découvrez comment NetApp permet la virtualisation du cloud hybride sur les principales plates-formes multicloud hybrides.  Regardez des vidéos présentant Red Hat OpenShift Service sur AWS (ROSA) avec les solutions FSx ONTAP et NetApp HCI pour les charges de travail virtualisées.



== Service Red Hat OpenShift sur AWS (ROSA) avec FSx ONTAP

.Amazon FSx for NetApp ONTAP avec Red Hat OpenShift Service sur AWS à l'aide du plan de contrôle hébergé
video::213061d2-53e6-4762-a68f-b21401519023[panopto,width=360]
.Intégration de FSx ONTAP avec Trident
video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto,width=360]
.Instantané/Restauration pour les applications sur les clusters Red Hat OpenShift Service sur AWS (ROSA) avec stockage Amazon FSx ONTAP
video::36ecf505-5d1d-4e99-a6f8-b11c00341793[panopto,width=360]
.Basculement et restauration des applications sur ROSA avec FSx ONTAP
video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto,width=360]


== Solutions NetApp HCI

.NetApp HCI pour Red Hat OpenShift sur Red Hat Virtualization
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]