---
sidebar: sidebar 
permalink: opennebula/opennebula-ontap-fc.html 
keywords: netapp, opennebula, lvm thin, fc, fibre channel, lvm, ontap, storage 
summary: 'Configurez le datastore Logical Volume Manager (LVM) avec Fibre Channel pour OpenNebula en utilisant ONTAP. Cette procédure comprend la configuration multipath, le provisionnement des LUN, la configuration des igroups et la création d"un groupe de volumes pour le datastore partagé.' 
---
= Configurer LVM Thin avec ONTAP FC pour OpenNebula
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Configurez un datastore Logical Volume Manager (LVM) pour le stockage partagé entre les hôtes OpenNebula en utilisant le protocole Fibre Channel avec NetApp ONTAP. Cette configuration permet un accès au stockage bloc avec des performances élevées et une faible latence.



== Tâches initiales de l'administrateur de virtualisation

Effectuez ces tâches initiales pour préparer les hôtes OpenNebula à la connectivité FC et recueillir les informations nécessaires pour l'administrateur de stockage.

. Vérifiez que deux interfaces HBA sont disponibles.
. Assurez-vous que multipath-tools est installé sur tous les hôtes OpenNebula et qu'il démarre au démarrage.
+
[role="tabbed-block"]
====
.Debian/Ubuntu
--
[source, shell]
----
apt list | grep multipath-tools
# If need to install, execute the following line.
apt-get install multipath-tools
# If /etc/multipath.conf is not present, first make sure the multipathd service is started.
systemctl enable --now multipathd
----
--
.RHEL/AlmaLinux
--
[source, shell]
----
dnf list installed | grep device-mapper-multipath
# If need to install, execute the following line.
dnf install device-mapper-multipath
# If /etc/multipath.conf is not present, first make sure the multipathd service is started.
systemctl enable --now multipathd
----
--
====
. Collectez le WWPN de tous les hôtes OpenNebula et fournissez-le à l'administrateur de stockage et à l'administrateur chargé du zonage du fabric.
+
[source, shell]
----
cat /sys/class/fc_host/host*/port_name
----




== Tâches de l'administrateur de stockage

Si vous débutez avec ONTAP, utilisez System Manager pour une meilleure expérience.

. Assurez-vous que le SVM est disponible avec le protocole FC activé. Suivre link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Documentation ONTAP 9"].
. Créez deux LIF par contrôleur dédiées au FC. Récupérez les adresses WWPN des LIF FC créées et fournissez-les à l'administrateur qui s'occupe du zonage de la structure.
. Créez un igroup et renseignez les initiateurs FC hôtes. En général, un igroup est créé pour un cluster OpenNebula. Incluez les serveurs frontaux et les hôtes hyperviseurs dans le même igroup pour prendre en charge les datastores Image et System.
. Créez le LUN de la taille souhaitée sur le SVM et présentez-le à l'igroup créé à l'étape précédente. Assurez-vous que la protection anti-ransomware est activée dans l'onglet Sécurité pour les systèmes ASA et dans l'onglet Sécurité des volumes pour les systèmes AFF/ FAS .
. Informez l'administrateur de virtualisation que le LUN a été créé.




== Tâches finales de l'administrateur de virtualisation

Effectuez ces tâches pour configurer le LUN FC en tant que banque de données LVM partagée dans OpenNebula.

. Connectez-vous en SSH à tous les serveurs OpenNebula et effectuez les étapes suivantes sur chaque hôte.
. Exécutez  `rescan-scsi-bus.sh` ou  `echo "- - -" > /sys/class/scsi_host/host*/scan` pour analyser à nouveau le bus SCSI et détecter les nouveaux LUN.
. Vérifiez que le LUN est visible sur tous les hôtes OpenNebula à l'aide de  `lsblk -S` ou de la commande fdisk -l. Notez le nom du périphérique (par exemple, sde, sdf) pour le LUN créé.
. Ajoutez le périphérique à la configuration multipath en exécutant  `multipath -a /dev/<device_name>`. Ensuite, exécutez  `multipath -r` pour recharger la configuration multipath. Vérifiez la configuration multipath en exécutant la commande  `multipath -ll`.
. Connectez-vous en SSH à l'un des serveurs frontaux et créez un fichier de configuration en fonction du type de Datastore souhaité. Pour obtenir la liste complète des attributs, consultez  https://docs.opennebula.io/7.0/product/cluster_configuration/san_storage/lvm_drivers/["OpenNebula documentation LVM"]. Des exemples de fichiers sont présentés ci-dessous :
+
[role="tabbed-block"]
====
.Sauvegarde
--
.. Pour Restic,


[listing]
----
$cat fc-restic.conf
NAME = "Backup-Restic-FC"
TYPE = "BACKUP_DS"

DS_MAD = "restic"
TM_MAD = "-"

RESTIC_PASSWORD = "<restic_password>"
RESTIC_SFTP_SERVER = "<backup server>"
----
.. Pour Rsync,


[listing]
----
$cat fc-rsync.conf
NAME = "Backup-Rsync-FC"
TYPE = "BACKUP_DS"

DS_MAD = "rsync"
TM_MAD = "-"

RSYNC_USER = "<rsync_user>"
RSYNC_HOST = "<backup server>"
----
--
.Fichier
[source, shell]
----
$cat fc-kernel.conf
NAME = "File-Kernel-FC"
TYPE = "FILE_DS"
DS_MAD = "fs"
TM_MAD = "local"
SAFE_DIRS = "/var/tmp/files"
----
.Image
[source, shell]
----
$cat fc-image.conf
NAME = "Image-FC01"
TYPE = "IMAGE_DS"
DS_MAD = "fs"
TM_MAD = "fs_lvm_ssh"
DISK_TYPE = "block"
LVM_THIN_ENABLE = "yes"
----
.Système
[source, shell]
----
$cat fc-system.conf
NAME = "System-FC02"
TYPE = "SYSTEM_DS"
TM_MAD = "fs_lvm_ssh"
DISK_TYPE = "block"
BRIDGE_LIST = "<space-separated list of OpenNebula hosts>" # If LUN not presented to frontend hosts
LVM_THIN_ENABLE = "yes"
----
====
. Exécutez  `onedatastore create <configuration file>`. Notez l’identifiant du datastore renvoyé après la création.
+
[]
====
onedatastore create fc-system.conf ID : 107

====
. Créez un groupe de volumes sur le LUN FC à l'aide de la commande  `vgcreate <vg_name> <multipath_device>`. Pour les banques de données d'images, le nom du groupe de volumes peut être choisi librement. Pour les banques de données système, le nom du groupe de volumes doit être au format  `vg-one-<datastore id>`. Ceci est nécessaire pour que OpenNebula identifie le groupe de volumes correct pour les banques de données système. Poursuivez les étapes suivantes si vous créez une banque de données de sauvegarde, de fichiers ou d'images. Pour les banques de données système, arrêtez-vous ici.
. Créez un pool de volumes logiques léger à l'aide de la commande  `lvcreate -l 100%FREE -n <logical volume name> <volume group name>`. Pour les banques de données système, OpenNebula crée automatiquement le pool LVM léger lorsque cela est nécessaire.
. Créez un système de fichiers sur le volume logique à l'aide de la commande  `mkfs.ext4 /dev/<volume group>/<logical volume>`. Les banques de données système ne nécessitent pas la création d'un système de fichiers.
. Mettez à jour /etc/fstab ou la configuration d'automount pour monter le datastore avec les options de montage souhaitées. En supposant que l'emplacement par défaut du datastore est /var/lib/one/datastores. Peut être validé avec `onedatastore show <datastore_id>`. Sinon, vérifiez le paramètre DATASTORE_LOCATION dans /etc/one/oned.conf. Assurez-vous que le dossier <datastore_id> existe sous l'emplacement des datastores. Des exemples d'entrées sont présentés ci-dessous :
+
[role="tabbed-block"]
====
.Utilisation de /etc/fstab
--
[source, shell]
----
/dev/<vg name>/<logical volume> /var/lib/one/datastores/<datastore_id> ext4 _netdev,noauto,x-systemd.automount,nofail 0 2
----
--
.Utilisation du montage automatique
--
[source, shell]
----
/var/lib/one/datastores/<datastore_id> -fstype=ext4,_netdev,noauto,x-systemd.automount,nofail,rw :/dev/<vg name>/<logical volume>
----
--
====
. Montez le datastore à l'aide de  `mount -a` ou  `systemctl reload autofs` commande.
. Vérifiez que la banque de données est montée avec la commande mount et vérifiez la capacité de la banque de données avec la commande  `onedatastore show <datastore_id>`.
. Assurez-vous que l'utilisateur et le groupe oneadmin sont propriétaires du dossier du datastore. Ajustez les permissions à l'aide de la commande  `chown -R oneadmin:oneadmin /var/lib/one/datastores/<datastore_id>`.

